language: c
sudo: required
dist: xenial
matrix:
  include:
    - compiler: gcc
      env: CFLAGS="--coverage" LDFLAGS"=--coverage" COVERAGE=yes
    - arch: arm64
      compiler: gcc
      env: CFLAGS="--coverage" LDFLAGS"=--coverage" COVERAGE=yes
    
before_install:
  - if [ -n "${COVERAGE}" ]; then pip install --user pyyaml cpp-coveralls; fi
  - export CFLAGS="$CFLAGS -Werror -Wall -Wextra -pedantic"
  - export CXXFLAGS="$CFLAGS"
script:
  - cmake . -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
  - cmake --build .
  - ctest -V
  - sudo make install
  - |-
    if [ -n "${EXTTESTS}" ]; then
        for exttest in exttests/*; do
            (
                echo "Running exttest $exttest..."
                cd $exttest
                if [ -e CMakeLists.txt ]; then
                    cmake . >/dev/null 2>&1 || cmake .
                fi
                make >/dev/null 2>&1 || make
            )
        done
    fi
after_success:
  - if [ -n "${COVERAGE}" ]; then coveralls -i libversion; fi
